- name: variables
  hosts: local
  connection: local
  vars: # PLAY level variables, Global variables
    COURSE: "DevOps with AWS"
    DURATION: 120hrs
    TRAINER: siva kumar reddy
  tasks: 
  - name: print the variable
    ansible.builtin.debug:
      msg: "course is {{ COURSE }} , Duration {{ DURATION }}, Trainer is {{ TRAINER }}"

 
