- name: variables
  hosts: local
  connection: local
  tasks: 
  - name: pirnt the variable
    ansible.builtin.debug:
      msg: "course is DevOps with AWS, Duration 120hrs, Trainer is siva kumar reddy"
