- name: variables from files
  hosts: web
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: " course is {{ COURSE }}, duraion is {{ DURATION }}, trainer is {{ TRAINER }}" 