- name: variables 
  hosts: local
  connection: local
  vars: # play leevl variables
    GREET: "PLAY"
  vars_files:
  - course.yaml
  vars_prompt:
  - name: GREET
    prompt: Enter the value
    private: false
  tasks:
  - name: print course information
    vars:
      GREET: "TASK"
    ansible.builtin.debug:
      msg: "Hello from {{ GREET }}" 